'use client'
import './globals.css'
import * as React from 'react'
import { PropsWithChildren } from 'react'
import { darkTheme, lightTheme } from './theme/themes'
import { ThemeProvider, CssBaseline } from '@mui/material'
import { CartProvider } from './context/cartContext'
import NavAppBar from './components/common/Nav/nav'
import { BrowserRouter as Router } from 'react-router-dom'
import { ProductProvider } from './context/productContext'
import Footer from './components/common/Nav/Footer/Footer'

interface RootLayoutProps {
  // You can add props here if needed
}

export default function RootLayout({ children }: PropsWithChildren<RootLayoutProps>) {
  const [theme, setTheme] = React.useState(lightTheme)

  const toggleTheme = () => {
    setTheme(theme === lightTheme ? darkTheme : lightTheme)
  }

  return (
    <html lang='en'>
      <head>
        <title>kalex</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <ProductProvider>
            <CartProvider>
              <Router>
                {/* Pass theme and toggle function to NavAppBar */}
                <NavAppBar theme={theme} onThemeToggle={toggleTheme} />
                <div id='__next'>{children}</div>
                <Footer />
              </Router>
            </CartProvider>
          </ProductProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
